/** Curated list of common strength exercises, used to power add-exercise suggestions. */
export const EXERCISE_LIBRARY: readonly string[] = [
  // Chest
  'Bench Press',
  'Barbell Bench Press',
  'Incline Barbell Bench Press',
  'Decline Barbell Bench Press',
  'Dumbbell Bench Press',
  'Incline Dumbbell Press',
  'Decline Dumbbell Press',
  'Dumbbell Fly',
  'Incline Dumbbell Fly',
  'Cable Fly',
  'Cable Crossover',
  'Pec Deck',
  'Push-Up',
  'Weighted Push-Up',
  'Dips',
  'Weighted Dips',
  'Machine Chest Press',
  'Smith Machine Bench Press',
  'Landmine Press',
  'Svend Press',
  'Floor Press',

  // Back
  'Deadlift',
  'Romanian Deadlift',
  'Sumo Deadlift',
  'Deficit Deadlift',
  'Rack Pull',
  'Pull-Up',
  'Weighted Pull-Up',
  'Chin-Up',
  'Weighted Chin-Up',
  'Lat Pulldown',
  'Close-Grip Lat Pulldown',
  'Barbell Row',
  'Pendlay Row',
  'Dumbbell Row',
  'T-Bar Row',
  'Seated Cable Row',
  'Chest-Supported Row',
  'Face Pull',
  'Straight-Arm Pulldown',
  'Barbell Shrug',
  'Dumbbell Shrug',
  'Good Morning',
  'Back Extension',
  'Hyperextension',
  'Inverted Row',

  // Legs
  'Squat',
  'Back Squat',
  'Front Squat',
  'Box Squat',
  'Zercher Squat',
  'Overhead Squat',
  'Hack Squat',
  'Leg Press',
  'Bulgarian Split Squat',
  'Walking Lunge',
  'Reverse Lunge',
  'Step-Up',
  'Leg Extension',
  'Leg Curl',
  'Seated Leg Curl',
  'Lying Leg Curl',
  'Nordic Curl',
  'Hip Thrust',
  'Glute Bridge',
  'Cable Kickback',
  'Standing Calf Raise',
  'Seated Calf Raise',
  'Goblet Squat',
  'Sissy Squat',
  'Belt Squat',
  'Adductor Machine',
  'Abductor Machine',
  'Pistol Squat',
  'Trap Bar Deadlift',
  'Single-Leg Press',
  'Cossack Squat',

  // Shoulders
  'Overhead Press',
  'Push Press',
  'Seated Dumbbell Press',
  'Arnold Press',
  'Dumbbell Lateral Raise',
  'Cable Lateral Raise',
  'Front Raise',
  'Rear Delt Fly',
  'Reverse Pec Deck',
  'Upright Row',
  'Barbell Shoulder Press',
  'Machine Shoulder Press',
  'Cuban Press',
  'Landmine Lateral Raise',
  'Bradford Press',
  'Behind-the-Neck Press',
  'Y-Raise',
  'Plate Front Raise',
  'Band Pull-Apart',
  'Cable Y-Raise',

  // Arms
  'Barbell Curl',
  'EZ-Bar Curl',
  'Dumbbell Curl',
  'Hammer Curl',
  'Preacher Curl',
  'Concentration Curl',
  'Incline Dumbbell Curl',
  'Cable Curl',
  'Spider Curl',
  'Zottman Curl',
  'Close-Grip Bench Press',
  'Skull Crusher',
  'Tricep Pushdown',
  'Overhead Tricep Extension',
  'Tricep Kickback',
  'Diamond Push-Up',
  'Cable Overhead Extension',
  'JM Press',
  'Reverse Curl',
  'Wrist Curl',
  'Reverse Wrist Curl',
  'Cable Rope Hammer Curl',
  'Bench Dip',
  'Single-Arm Tricep Extension',
  'Drag Curl',

  // Core
  'Plank',
  'Side Plank',
  'Hanging Leg Raise',
  'Hanging Knee Raise',
  'Cable Crunch',
  'Weighted Sit-Up',
  'Russian Twist',
  'Ab Wheel Rollout',
  'Sit-Up',
  'Crunch',
  'Bicycle Crunch',
  'Toes to Bar',
  'Dead Bug',
  'Pallof Press',
  'Woodchopper',
  'Decline Sit-Up',
  'Flutter Kick',
  'V-Up',
  'Mountain Climber',
  'Landmine Rotation',

  // Olympic / Functional
  'Power Clean',
  'Hang Clean',
  'Clean and Jerk',
  'Snatch',
  'Hang Snatch',
  'Push Jerk',
  'Kettlebell Swing',
  'Kettlebell Snatch',
  "Farmer's Carry",
  'Box Jump',
  'Thruster',
  'Wall Ball',
  'Turkish Get-Up',
  'Clean Pull',
  'Snatch Pull',
] as const;
